[package]
name = "ns16550a"
version = "0.1.0"
edition = "2021"

[dependencies]
libglenda-rs = { path = "../../lib/libglenda-rs", features = ["rt-service"] }
spin = "0.10.0"

[features]
default = []
unicode = []
