[[driver]]
name = "ns16550a"
binary = "ns16550a"
type = "process"

[driver.match]
compatible = ["ns16550a", "snps,dw-apb-uart"]

[[driver]]
name = "virtio-blk"
binary = "virtio-blk"
type = "process"

[driver.match]
compatible = ["virtio,mmio"]
device_id = 2 # VirtIO Block Device ID
