[package]
name = "dtb"
version = "0.1.0"
edition = "2021"

[dependencies]
glenda-drivers = { path = "../../../lib/libglenda_drivers-rs", package = "libglenda_drivers-rs" }
fdt = "0.1.5"
libglenda-rs = { path = "../../../lib/libglenda-rs", features = ["rt-service"] }
