[package]
name = "virtio-net"
version = "0.1.0"
description = "VirtIO-Net driver for Glenda Microkernel"
edition = "2021"

[dependencies]
libglenda-rs = { path = "../../../lib/libglenda-rs", features = ["rt-service"] }
virtio-common = { path = "../common" }
